version: "3.9"
services:

  inventario-api-image:
    image: inventario-api-image
    container_name: inventario-api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 9774676Dl
    networks:
      - spring-network
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: ronnie2001
      MYSQL_DATABASE: inventario_db
      MYSQL_USER: admin_user
      MYSQL_PASSWORD: 9774676Dl
    ports:
      - "3307:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  spring-network:
volumes:
  mysql-volume:
